# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170320_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='annonymous', max_length=50),
            preserve_default=False,
        ),
    ]
